# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  log_level:
    description: |
      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  tracing_enabled:
    description: |
      Acceptable values are: 0 for false and anything else for true
    default: True
    type: boolean
