# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  log-level:
    description: |
      Configures the log level of gunicorn. 

      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  kratos_url:
    description: Kratos API URL. In the final version the operator uses the interface relation to get Kratos API URL. Config value is a fallback.
    type: string
    default: "DEFAULT-KRATOS-PLACEHOLDER"
  hydra_url:
    description: Hydra API URL. In the final version the operator uses the interface relation to get Hydra API URL. Config value is a fallback.
    type: string
    default: "DEFAULT-HYDRA-PLACEHOLDER"
  port:
    description: The port where the Identity Platform Login UI is Accessible
    type: string
    default: "8080"
