name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@5bb665b2e346c38f5f081c85a6282802afe96512 # v1.7.7
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
