name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@81e8eeaa58cf2f549cf229f139e56810d0d84e2c # v1.6.0
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
