name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@0815f8e87456fd72fdcb68097dae31606ceb01ef # v1.5.0
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
