name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   workflow_call:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
       - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@dfa29853f47f32bbe2974ad021d067ae245452f8 # v1.7.5
    with:
      charm-name: "identity-platform-login-ui-operator"
      container-name: "login-ui"
      use-charmcraftcache: true
