name: On Schedule
on:
  schedule:
    - cron: '0 8 * * MON'

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@0815f8e87456fd72fdcb68097dae31606ceb01ef # v1.5.0
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@81e8eeaa58cf2f549cf229f139e56810d0d84e2c # v1.6.0
    with:
      charm-name: "identity-platform-login-ui-operator"
      container-name: "login-ui"
      use-charmcraftcache: true
