name: On Schedule
on:
  schedule:
    - cron: '0 8 * * MON'

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@dfa29853f47f32bbe2974ad021d067ae245452f8 # v1.7.5
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@dfa29853f47f32bbe2974ad021d067ae245452f8 # v1.7.5
    with:
      charm-name: "identity-platform-login-ui-operator"
      container-name: "login-ui"
      use-charmcraftcache: true
