# Publish login_ui_endpoints library only if it has changed
name: Publish library

on:
  push:
    branches:
      - main
    paths:
      - "./lib/charms/identity_platform_login_ui_operator/v0/login_ui_endpoints.py"

jobs:
  publish-lib:
    name: Publish library
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install charmcraft
        run: sudo snap install charmcraft --channel latest/stable --classic

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
        run: |
          charmcraft publish-lib charms.identity_platform_login_ui_operator.v0.login_ui_endpoints