name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release:
      name: release
      uses: canonical/identity-team/.github/workflows/charm-release.yaml@2944c3a340c5f5b63459f233cb6f53860da66bf1 # v1.4.1
      secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
