name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:   
          token: ${{ secrets.PAT_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json
          # target adjusts for track releases
          target-branch: ${{ github.ref_name }}
          # ensure release-please manifest has the component set to track-<version> in track branches
          include-component-in-tag: ${{ contains(github.ref_name, 'track') }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - if: ${{ steps.release.outputs.pr != '' }}
        run: |
          gh pr merge --auto --merge ${{ fromJSON(steps.release.outputs.pr).number }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
