# Release login_ui_endpoints library only if it has changed
name: Release library

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/identity_platform_login_ui_operator/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@3bcf7c8d36b4e51e5a65d27041389d7456c17b57 # v1.8.0
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
