# Release login_ui_endpoints library only if it has changed
name: Release library

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/identity_platform_login_ui_operator/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@f18247249f506f3c9210b86e43a2c4dd063088c5 # v1.8.7
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
