# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_dispatch:

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@0815f8e87456fd72fdcb68097dae31606ceb01ef # v1.5.0
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
