# reusable workflow for automatically approving PRs updating charm libraries
name: Approve Updating Charm Libraries
run-name: CI for approving automated-update-charm-libs PRs

on:
  push:
    branches:
      - "automated-update-charm-libs"

jobs:
  autoapprove:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Approve PR
        run: |
          gh pr review --approve || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
